### ISSUE TITLE
Tiny window when copying, moving files

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1441]
## Problem

In Helm 1.9.3, when trying to copy or move (rename) files, the Helm window becomes tiny:

![helm-rename-tiny-window](https://cloud.githubusercontent.com/assets/1624090/13972628/55facbc6-f068-11e5-8503-4a2b7c5460b7.png)

After copying or moving the file, the Helm buffer disappears, but leaves the tiny window in place.

**Update**: this behavior seems to appear only for some values of the `helm-split-window-default-side` variable. See [comment below](https://github.com/emacs-helm/helm/issues/1441#issuecomment-200200449) for more information.

## Suggested Behavior

Maintain the Helm window size, and restored the Helm buffer after the action. It is likely that the user would like to continue using Helm after the action is performed.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Problem
>
> In Helm 1.9.3, when trying to copy or move (rename) files, the Helm
> window becomes tiny:

I cannot reproduce this.

> After copying or moving the file, the Helm buffer disappears, but
> leaves the tiny window in place.

And this too.

Did you try starting with emacs-helm.sh ?

-- 
Thierry

**Comment by xiongtx** [comment]
I can replicate this with `emacs-helm.sh` when `helm-split-window-default-side` is set to `same`, but not when it is set to `below`, which is the default.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> I can replicate this with emacs-helm.sh when
> helm-split-window-default-side is set to same,

Ok so this is the problem.
This configuration is rarely used, I have to fix it with 
with-helm-display-marked-candidates.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Should be fixed now, please confirm.

Thanks.

**Comment by xiongtx** [comment]
Well...the window is no longer small, but now the window configuration changes so that nothing when renaming files, the horizontal split becomes a vertical split.

It'd be better if the window configuration was kept the same, but it that's not possible/worthwhile, I'll mark this as resolved.

**Comment by thierryvolpiatto** [comment]
Your

**Comment by xiongtx** [comment]
OK, that's fine. Thanks!

**Comment by jagrg** [comment]
I'm still seeing the problem. Steps to reproduce using `emacs-helm.sh`:

1. Open a dired buffer;
2. Press `m` and mark two files;
3. Press `R` (dired-do-rename) to rename them.

The window is too small. I think the problem is with the helm buffer which is created on top of the shrunk window, in particular when `dired-shrink-to-fit` is set to t (which it is by default).

When doing the same steps with Ido, the small window is created above the minibuffer displaying the marked files. What happens otherwise is that Helm uses this tiny window created by the dired command to build its window. For now, the easiest fix is probably to set `dired-shrink-to-fit` to nil.

**Comment by jagrg** [comment]
`(setq helm-always-two-windows t)` works too.

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> (setq helm-always-two-windows t) works too.

Yes this is what needed, dired-shrink-to-fit does nothing here.
When copying/renaming etc.. files from helm-find-files windows are
displayed properly because helm let-bind helm-always-two-windows.
I have commited a change that make this also happen in dired.
Be sure to update your helm-completing-read-handlers-alist according to
default to make it works.

Thanks.

-- 
Thierry

**Comment by jagrg** [comment]
Thanks, Thierry, it's working well now.
