### ISSUE TITLE
helm-imenu-in-all-buffer not working in enh-ruby-mode

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#1704]
`helm-imenu` is worked, but `helm-imenu-in-all-buffer` is not worked.

1.  open a rb file with enh-ruby-mode, https://github.com/zenspider/enhanced-ruby-mode

2. press my binding key (e.g. C-c j), no any indexed content is displayed, if used with `helm-menu`,
    it worked.

3. when I input some content try to filter out, minibuffer got message:  `Imenu indexing buffers...done`

4. if use `ruby-mode` + `js-mode`, it worked

5. seem like, `helm-imenu-in-all-buffer` just not worked in `enh-ruby-mode`

Following is my config:

```cl
(require 'helm-imenu)
(with-eval-after-load 'helm-imenu
  (global-set-key [(control c) (j)] 'helm-imenu)
  ;; (custom-set-variables '(helm-imenu-fuzzy-match t))
  (add-hook 'prog-mode-hook
            #'(lambda ()
                (local-set-key [(control c) (j)] 'helm-imenu-in-all-buffers)))
  (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . js2-mode))
  (add-to-list 'helm-imenu-all-buffer-assoc  '(enh-ruby-mode . js2-mode))
  (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . html-mode))
  (add-to-list 'helm-imenu-all-buffer-assoc  '(enh-ruby-mode . html-mode))
  (add-to-list 'helm-imenu-all-buffer-assoc  '(js2-mode . html-mode)))
```

Thanks

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

>  5. seem like, helm-imenu-in-all-buffer just not worked in enh-ruby-mode

Is M-x imenu working with enh-ruby-mode enabled ?
    
-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

>  5. seem like, helm-imenu-in-all-buffer just not worked in enh-ruby-mode

Hmm, Don't understand, if helm-imenu is working there is no reasons
helm-imenu-in-all-buffer is not working.

Any chances to download the rb project you are using so that I can
reproduce ?

-- 
Thierry

**Comment by zw963** [comment]
>> Is M-x imenu working with enh-ruby-mode enabled ?

helm-imenu and imenu both worked.

**Comment by zw963** [comment]
>> Any chances to download the rb project you are using so that I can
reproduce ?

In fact, any project which use enh-ruby-mode is not worked.

this project is a example,  in this file : https://github.com/zw963/erb_to_slim/blob/master/lib/erb_to_slim/engine.rb

`helm-imenu` is worked
`imenu` is worked
`helm-imenu-in-all-buffer` not worked. : (

```cl
Imenu indexing buffers...done
equal: Wrong type argument: listp, "*helm imenu all*"
```

**Comment by zw963** [comment]
Hi, I have tried in almost pure emacs to reproduce this issue:

1. start emacs with empty config. and settings correct `LOAD-PATH`
2. eval-expression: (require 'enh-ruby-mode)
3. eval-expression: (require 'helm-config)
4. open a rb file , M-x enh-ruby-mode
5. M-x helm-imenu, worked
6. M-x helm-imenu-in-all-buffers, not worked

emacs: 25.1
enh-ruby-mode backed ruby is traveling version ruby-2.1.6 https://github.com/phusion/traveling-ruby
`helm-imenu-all-buffer-assoc` is nil

**Comment by xiongtx** [comment]
The `Imenu indexing buffers...done` message seems to be repeated with each keystroke when `helm-imenu-candidates-in-all-buffers` returns `nil`. This can be seen by calling `helm-imenu-in-all-buffers` from an empty `*scratch*` buffer with no other `emacs-lisp-mode` buffers. This should probably be treated as a bug in its own right.

For `enh-ruby-mode`, `helm-imenu-candidates-in-all-buffers` returns `nil` b/c of the following:

```emacs-lisp
(and (with-current-buffer b
       (derived-mode-p 'prog-mode))
     (with-current-buffer b
       (helm-same-major-mode-p helm-current-buffer
                               helm-imenu-all-buffer-assoc)))
```

`enh-ruby-mode` derives from `enh-ruby-parent-mode`, which is an *alias* for `prog-mode`, but which results in `(derived-mode-p 'prog-mode')` returning `nil`.

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> In fact, any project which use enh-ruby-mode is not worked.

I am unable to make enh-ruby-mode working at all, it fails immediately
leaving me unable to kill engine.rb buffer, so I had no chances to try
imenu or whatever.

> Imenu indexing buffers...done
> equal: Wrong type argument: listp, "*helm imenu all*"

So, good you have an error here, can you send the backtrace please ?


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> Hi, I have tried in almost pure emacs to reproduce this issue:
>
>  1. start emacs with empty config. and settings correct LOAD-PATH
>  2. eval-expression: (require 'enh-ruby-mode)
>  3. eval-expression: (require 'helm-config)
>  4. open a rb file , M-x enh-ruby-mode
>  5. M-x helm-imenu, worked
>  6. M-x helm-imenu-in-all-buffers, not worked
>
> emacs: 25.1
> enh-ruby-mode backed ruby is traveling version ruby-2.1.6 https://github.com/phusion/traveling-ruby
> helm-imenu-all-buffer-assoc is nil

enh-ruby-mode fails at 4. so I am unable to try 5. and 6.
Can you please send the backtrace ?

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> The Imenu indexing buffers...done message seems to be repeated with
> each keystroke when helm-imenu-candidates-in-all-buffers returns
> nil. This can be seen by calling helm-imenu-in-all-buffers from an
> empty *scratch* buffer with no other emacs-lisp-mode buffers. This
> should probably be treated as a bug in its own right.

What makes you thinking this is a bug ?
I see nothing wrong here.


--
Thierry

**Comment by xiongtx** [comment]
> What makes you thinking this is a bug ?

Because most Helm sources, when they are empty, do not constantly emit messages while the user is typing.

**Comment by zw963** [comment]
> The Imenu indexing buffers...done message seems to be repeated with each keystroke when helm-imenu-candidates-in-all-buffers returns nil

Yes, it repeat when each keystroke.

**Comment by xiongtx** [comment]
@zw963 Your problem should be fixed with [my `enh-ruby-mode` branch](https://github.com/zenspider/enhanced-ruby-mode/pull/105).

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

>     What makes you thinking this is a bug ?
>
> Because most Helm sources, when they are empty, do not constantly emit
> messages while the user is typing.

Oh yes I didn't try to type with the empty helm-buffer, will fix this
soon.

Thanks to catch this.

--
Thierry

**Comment by zw963** [comment]
@thierryvolpiatto , sorry, I have no idea about output those messages.

I set `(setq debug-on-error t)` and  `(setq debug-on-signal t)`, no anythings output ...

In fact,  `equal: Wrong type argument: listp, "*helm imenu all*"` is happen when I 
try to switch out to another buffer when cursor is in minibuffer, it seem like not relation
to this bug.

**Comment by zw963** [comment]
@xiongtx , seem like not fixed completely.

following is reproduce:

1. add config `(add-to-list 'helm-imenu-all-buffer-assoc  '(enh-ruby-mode . js-mode))`
2.  reboot emacs
3. open a new rb file
4. M-x helm-imenu-in-all-buffer is worked
5. open a new js file
6. M-x helm-imenu-in-all-buffer is worked
7. from js jump to previous rb file
8. M-x helm-imenu-in-all-buffer,  `Imenu indexing buffers...done` again.

thanks

**Comment by xiongtx** [comment]
@zw963 Cannot reproduce.

**Comment by thierryvolpiatto** [comment]
With @xiongtx https://github.com/zenspider/enhanced-ruby-mode/pull/105 and commit  9fefcf2 your bug should be now fixed, please confirm (and close if ok for you).

Thanks.

**Comment by zw963** [comment]
@thierryvolpiatto , A little busy, sorry, I will confirm this issue today with a bare config emacs
and close this issue is it fixed.

**Comment by zw963** [comment]
Sorry for late confirm! I have tried almost a pure config, But this hack is not worked well for me.

Seem like some issue exist in helm.

When switch to `js-mode`, it worked as expect, But switch back to `enh-ruby-mode`,
could not found the entries which in `js-mode`.

following is my config:
```cl
(require 'enh-ruby-mode)
(with-eval-after-load 'enh-ruby-mode
  (setq enh-ruby-deep-indent-paren nil)        ;括号中的列表深度缩进。
  (setq enh-ruby-add-encoding-comment-on-save nil)
  (setq enh-ruby-program "/some/path/for/ruby-2.1.6"))
(let ((preferred-ruby-mode (if (fboundp 'enh-ruby-mode) 'enh-ruby-mode 'ruby-mode)))
  (add-to-list 'auto-mode-alist
               `("\\.\\(rb\\|rake\\|ru\\|gemspec\\|jbuilder\\|rjs\\)\\'"
                 . ,preferred-ruby-mode))
  (add-to-list 'auto-mode-alist
               `("\\`Rakefile\\|Gemfile\\|Capfile\\|Guardfile\\'"
                 . ,preferred-ruby-mode))
  (add-to-list 'interpreter-mode-alist `("ruby" . ,preferred-ruby-mode)))

;; (require 'my-customized-helm-settings nil t)
(require 'helm-config)
(require 'helm-imenu)
(with-eval-after-load 'helm-imenu
  (add-hook 'prog-mode-hook
            #'(lambda ()
                (local-set-key [(control c) (j)] 'helm-imenu-in-all-buffers)
                ))
  (add-to-list 'helm-imenu-all-buffer-assoc  '(enh-ruby-mode . js-mode))
  )
```

This ruby-2.1.6 can be download from here. https://d6r77u77i8pq3.cloudfront.net/
we need a ruby Interpreter to make `enh-ruby-mode` work well.

Following is two gists which one ruby file and one js file. for example can switch between.

js example: https://gist.github.com/zw963/a779e5f16b3d7e0337b749f91b074b55
rb example: https://gist.github.com/zw963/614a582d6c8f392ca95c0bd48019a0b3

**Comment by zw963** [comment]
@thierryvolpiatto , after update to newest helm, f266bb6

When I run `helm-imenu-in-all-buffer`, nothing is list in cadicates.
in fact, `helm-imenu` is not worked in `enh-ruby-mode`.

but all worked well in `js-mode` ...

**Comment by thierryvolpiatto** [comment]
I am afraid you will have to find by yourself what is happening with enh-ruby-mode and send here a usable backtrace, without this I am unable to guess what's wrong.
I am for now unsure there is a bug with helm but I tend to say something is going wrong with enh-ruby-mode (just an assumption).

**Comment by zw963** [comment]
@xiongtx , With lastest helm (f266bb6), you still worked well?

Thanks.

**Comment by xiongtx** [comment]
`helm-imenu` seems to have broken for not just `enh-ruby-mode`, but regular `ruby-mode` as well. Works fine for `emacs-lisp-mode`.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> helm-imenu seems to have broken for not just enh-ruby-mode, but
> regular ruby-mode as well.

Thanks, should be fixed now.

--
Thierry

**Comment by zw963** [comment]
Thanks a lot, I will try some days ...
