### ISSUE TITLE
Helm mark functions do not move the cursor at the right column

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1770]
This is basically #709 which I believe was closed a bit early.

@thierryvolpiatto You said it is a detail, but there is a use case where the current behaviour is inconvenient.

Using standard Emacs, I can set a mark then move the cursor to create a selection. If only then I realize that the first mark is not at the right spot, I can rectify that with `C-x C-x` (`exchange-point-and-mark`).

Helm mark functions (e.g. `helm-mark-or-exchange-rect`) almost allows to do that, but the point is moved to the beginning of the column when exchanging point and mark.

This forces me to use two bindings (the original `exchange-point-and-mark` and 	`helm-mark-or-exchange-rect` for the general case) instead of one.

helm: 20170419.2242
OS: Arch Linux
Emacs: 25.2

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> This forces me to use two bindings (the original
> exchange-point-and-mark and helm-mark-or-exchange-rect for the general
> case) instead of one.

Should work now how you are expecting.
I don't know what is helm-mark-or-exchange-rect though.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Thanks!

Sorry for the confusion with `helm-mark-or-exchange-rect`, I forgot it was of my own:

```
(defun helm-mark-or-exchange-rect ()
  "Run `helm-all-mark-rings' or `rectangle-exchange-point-and-mark' if in rectangle-mark-mode."
  (interactive)
  (if rectangle-mark-mode
      (rectangle-exchange-point-and-mark)
    (helm-all-mark-rings)))
```

Let's forget that and use `helm-all-mark-rings` instead.

In terms of column position, it seems to work.
In terms of usability, it is still not quite superseding `exchange-point-and-mark`.

With `exchange-point-and-mark`:
- Mark
- Move the cursor to the desired position.
- `exchange-point-and-mark` to fix the initial mark.

With `helm-all-mark-rings`:
- Mark
- Move the cursor to the desired position.
- Mark again.
- `helm-all-mark-rings`
- select second entry and fix the initial mark.

The functions don't save the same purpose, but I'm wondering if there is a way to supersede exchange-point-and-mark elegantly.

**Comment by Ambrevar** [comment]
I found a solution that seems to work pretty well:

```
(defun helm-all-mark-rings-before-mark-point ()
  "Call `helm-all-mark-rings' before pushing the former point to the mark ring.
In Transcient Mark mode, this allows for rectifying the initial mark."
  (interactive)
  (let ((pos (point)) )
    (helm-all-mark-rings)
    (push-mark pos)))
```

The workflow is as follows:

- Mark
- Move the cursor to the desired position.
- `helm-all-mark-rings-before-mark-point`
- Confirm and fix the initial mark.

Compared to Emacs original behaviour, it is only one more key press.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> In terms of usability, it is still not quite superseding exchange-point-and-mark.

The purpose of helm-mark-ring is to store visited positions to retrieve
them quickly, I still don't understand what you want to do with
`exchange-point-and-mark`.

> With exchange-point-and-mark:
>
>   * Mark
>   * Move the cursor to the desired position.
>   * exchange-point-and-mark to fix the initial mark.

If you want to save the new position why don't you hit C-space twice ?

Note that all the helm search functions are saving position to mark-ring
when leaving this position, before this recent change helm-mark-ring was
doing this too we have to restore this, perhaps it is this that is
missing for you ?

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
I pushed a change that save current position to mark-ring before jumping
to a mark with helm-mark-ring, have a try.

PS: Ensure you use the default value of `helm-goto-line-before-hook`.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
> The purpose of helm-mark-ring is to store visited positions to retrieve
> them quickly, I still don't understand what you want to do with
> `exchange-point-and-mark`.

Just that: use helm-mark-ring's functions to store `point` and then retrieving the last mark, thus effectively doing the same thing as `exchange-point-and-mark`.

> If you want to save the new position why don't you hit C-space twice ?

Because as I detailed above, before commit b518c23  it was 1 more mark + 1 more selection in the helm buffer. Not convenient.

> Note that all the helm search functions are saving position to mark-ring
> when leaving this position, before this recent change helm-mark-ring was
> doing this too we have to restore this, perhaps it is this that is
> missing for you ?

Which recent change?

Anyways, this is exactly what was missing for me, it works well. Consider it solved!

**Comment by thierryvolpiatto** [comment]
Great, closing now.

Thanks.
