### ISSUE TITLE
Helm completion of subdir shell paths

### ISSUE THREAD

**Issue by WorldsEndless** [emacs-helm/helm#888]
When Helm auto completes shell paths, whether in shell mode or in `shell-command`, the preceding path is deleted upon completion. You can see what I mean with the following recipe: 

1. `m-x shell`
2. `ls` surface-directory-with-subdirs/ TAB
3. A list of subdirs to choose from will appear. Select one. 
- Now see the problem. What should be `surface-directory-with-subdirs/subdir` is, instead, just `subdir`, which will break any cp/mv/ls/etc command. 

GNU Emacs 25.0.50.6 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.9) of 2015-02-10 on localhost.localdomain

**Comment by michael-heerdegen** [comment]
FWIW I can't reproduce this here with helm.sh.

**Comment by thierryvolpiatto** [comment]
Tory S. Anderson <notifications@github.com> writes:

> When Helm auto completes shell paths, whether in shell mode or in
> shell-command, the preceding path is deleted upon completion. You can
> see what I mean with the following recipe:

Should work now.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by WorldsEndless** [comment]
Fixed it is. Thanks! I'd love to know how you did it, though, because I was also unable to reproduce it in helm.sh, leading me to believe it was some obscure conflict?

**Comment by thierryvolpiatto** [comment]
Tory S. Anderson <notifications@github.com> writes:

> Fixed it is. Thanks! I'd love to know how you did it, though, because
> I was also unable to reproduce it in helm.sh, leading me to believe it
> was some obscure conflict?

I could reproduce it in emacs-helm.sh also, the problem is the predicate
to decide if we are completing filenames of something else.
The completion code in emacs is hairy and it is difficult to (re)use its
API, we must reinvent things in some places.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by WorldsEndless** [comment]
This seems to still occur if a component of the path includes escape chars. Recipe (in shell):
 
    mkdir -p dir1/dir\ 2/dir\ 3
    <torys> temp/ 07:48$ tree dir1
    dir1
    └── dir\ 2
	└── dir\ 3

    2 directories, 0 files
    $ cd dir1/dir\ 2/ `TAB` 

The last command, typing out the paths and pressing TAB for auto-complete, will erase the rest of the path when dir\ 3 is selected.

**Comment by thierryvolpiatto** [comment]
Tory S. Anderson <notifications@github.com> writes:

> This seems to still occur if a component of the path includes escape chars. Recipe (in shell):
>
> mkdir -p dir1/dir\ 2/dir\ 3
> <torys> temp/ 07:48$ tree dir1
> dir1
> └── dir\ 2
> └── dir\ 3
>
> 2 directories, 0 files
> $ cd dir1/dir\ 2/ `TAB` 
>
> The last command, typing out the paths and pressing TAB for
> auto-complete, will erase the rest of the path when dir\ 3 is
> selected.

Indeed, thanks.
I will have to make a better predicate :-( as nothing is provided AFAIK
by emacs.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by WorldsEndless** [comment]
Looks good. Thanks!
