### ISSUE TITLE
helm-mini: Opening file from "recentf" in other frame or window should load buffer

### ISSUE THREAD

**Issue by cheezy64** [emacs-helm/helm#962]
Emacs 24.3.1
Helm 20150331

In helm-mini, if you select a file from "recentf" and press "C-c o" or "C-c C-o", it will either open a new window or frame with a blank buffer (named the full path of file).  I think it makes more sense to open the file if it's not yet loaded in the buffer.

For context of how I got into this situation -- I'm using a Macbook Pro and by default don't enable the Function keys.  So, I noticed when I was in the buffer list section, [tab] would show commands C-c o.  I had assumed the same key combinations worked on recentf, but (un)obviously not!

**Comment by tuhdo** [comment]
Hmm it does not happen for me on Emacs 24.4.

**Comment by thierryvolpiatto** [comment]
I think you are trying to open a deleted file, it is why you endup with an empty buffer.

**Comment by michael-heerdegen** [comment]
No, I see this too, with existing files.

In helm-mini, with a candidate of the recentf source selected, C-c C-o is actually bound to `helm-buffer-switch-other-frame' (why?) and if you actually type that, you get an empty buffer named after the file that had been selected.

**Comment by michael-heerdegen** [comment]
I've found the reason for the "why" above.  It's a bug:

In "helm-read-pattern-maybe", we do

```
(setq helm-map (or src-keymap any-keymap helm-map))
```

So, when you start "helm-mini", the local map of the minibuffer gets set to the value of "helm-buffer-map".

When you select a cand of the recentf source, "helm--maybe-update-keymap" changes "minor-mode-overriding-map-alist" so that helm--minor-mode refers to "helm-generic-files-map".

This leads to the situation that both "helm-generic-files-map" and "helm-buffer-map" are active, with the first taking precedence.  And because C-c C-o is not defined in the first one, the binding in the second one is executed.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I've found the reason for the "why" above. It's a bug:

It is not a bug.

> In "helm-read-pattern-maybe", we do
>
> (setq helm-map (or src-keymap any-keymap helm-map))
>
> So, when you start "helm-mini", the local map of the minibuffer gets
> set to the value of "helm-buffer-map".
>
> When you select a cand of the recentf source,
> "helm--maybe-update-keymap" changes "minor-mode-overriding-map-alist"
> so that helm--minor-mode refers to "helm-generic-files-map".

Yes and this take precedence on all other keymaps.

> This leads to the situation that both "helm-generic-files-map" and
> "helm-buffer-map" are active, with the first taking precedence.

No.

> And because C-c C-o is not defined in the first one, the binding in
> the second one is executed.

No, this is not a bug, the only reason is that C-c C-o is not bound in
this keymap, so the minibuffer inherit a C-c C-o from hell, I don't know
where.
It should be fixed now.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> > This leads to the situation that both "helm-generic-files-map" and
> > "helm-buffer-map" are active, with the first taking precedence.
>
> No.

Test it with this command:

(global-set-key
 [(control f12)]
 (defun helm-buffer-map-reachable-p ()
   (interactive)
   (message "helm-buffer-map %sactive"
            (if (memq helm-buffer-map (current-active-maps)) "" "not "))
   (sit-for 1)))

and try in M-x helm-mini.

> No, this is not a bug, the only reason is that C-c C-o is not bound in
> this keymap, so the minibuffer inherit a C-c C-o from hell, I don't
> know where.

I told you from where, but you didn't listen.  It took me one hour to
find it out.

> It should be fixed now.

The problem I described is still present.  It will manifest in any helm
session involving multiple sources.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> and try in M-x helm-mini.

I have not to try, I know helm-buffer-map is active (and it have to be
active), but is overhidden by minor-mode-overriding-map-alist.

Go in helm-for-files or helm-multi-files and use the command C-], you
will see it behave differently in each source.

> I told you from where, but you didn't listen. It took me one hour to
> find it out.

I am sorry you spend one hour to debug helm, but let me tell you I spend
actually hours and hours to implement the features you and others
request, so...please, thanks you.

>> It should be fixed now.
>
> The problem I described is still present. It will manifest in any helm
> session involving multiple sources.

Let me know if you encounter again such problems.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by cheezy64** [comment]
Michael, thanks for looking into it too.  I'm glad that someone else could reproduce it.

Thierry thanks for the great package.  The files from recentf still exist, but this command doesn't load them if it's not in the buffer.  However, the F3 and F4 keys which call another function will correctly open it.  I'll update the package tomorrow and see if I still see the behavior.

It sounds like you don't feel that it is a bug.  I think it's more of a usability type of issue if that's the case.  It makes more sense to me if the Keybindings in helm-mini are consistent regardless of which "category" we're in (eg Buffers or Recentf)

**Comment by cheezy64** [comment]
Ok, I figured out how to reproduce it reliably.  Please let me know if you're not able to reproduce it.

1) Execute helm-mini
2) Press the "right arrow" to move to the "Recentf" category. The first item should be highlighted now.
3) Press C-c C-o and notice how it opens a new frame, but instead of opening the file, it'll open a buffer with the whole file path as the buffer name

On the other hand, on step 2, if I type part of the file name until it filters to a file in RecentF, it's able open the file with C-c C-o.  Additionally, if you press "right arrow", then "down arrow", "up arrow" (to reselect the first file), and do C-c C-o, it works too

**Comment by tuhdo** [comment]
@cheezy64 Could you reproduce it from `emacs-helm.sh`? Because both from the script and from my own Helm configuration and in [Spacemacs](https://github.com/syl20bnr/spacemacs), I could not reproduce it.

**Comment by tuhdo** [comment]
May I look at your configuration?

**Comment by thierryvolpiatto** [comment]
cheezy64 <notifications@github.com> writes:

> Michael, thanks for looking into it too. I'm glad that someone else
> could reproduce it.
>
> Thierry thanks for the great package. The files from recentf still
> exist, but this command doesn't load them if it's not in the
> buffer. However, the F3 and F4 keys which call another function will
> correctly open it. I'll update the package tomorrow and see if I still
> see the behavior.
>
> It sounds like you don't feel that it is a bug. I think it's more of a
> usability type of issue if that's the case. It makes more sense to me
> if the Keybindings in helm-mini are consistent regardless of which
> "category" we're in (eg Buffers or Recentf)

It should work now, it is working here at least, with a file already
opened and not.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by cheezy64** [comment]
@tuhdo sure, I have it posted here:
https://github.com/cheezy64/dotemacs

I wasn't able to run emacs.sh since it was missing cl-lib.

I'll take a video and show you guys the behavior tomorrow.

**Comment by tuhdo** [comment]
Now I noticed that you are using Emacs 24.3. Maybe you should try Emacs 24.4 to see if the problem persists?

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> I have not to try, I know helm-buffer-map is active (and it have to be
> active), but is overhidden by minor-mode-overriding-map-alist.

Why does it have to be active?  helm-map should be active.

In a helm session with multiple sources, the local map in the minibuffer
is currently always the private keymap of the first source.  That
doesn't make sense.  If you say it's not so harmful, ok, but I wouldn't
say that it "should" be like that.

> I am sorry you spend one hour to debug helm, but let me tell you I
> spend actually hours and hours to implement the features you and
> others request, so...please, thanks you.

And I'm thankful for that.  Actually, that was one reason why I
spent a lot of time to debug this.

**Comment by thierryvolpiatto** [comment]
It's not harmful.

**Comment by cheezy64** [comment]
As an update, I do see this on and off, but I can't find a reliable way to reproduce it now.  Maybe it's a race condition of some sort or maybe my recentf file was just messed up.

**Comment by tuhdo** [comment]
It's possible you have old entries point to non-existent file. Make sure that the files you failed to open do exist.

**Comment by cheezy64** [comment]
Fixed!  
On my Mac, I switched from 24.3.1 to 24.5.1 and am no longer seeing the issue

**Comment by tuhdo** [comment]
@thierryvolpiatto The bug has been found. Does Helm still support Emacs 24.3?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto The bug has been found. Does Helm still support Emacs 24.3?

There is no relation with the emacs version, he just changed of emacs
after I fixed the bug, it is working on all emacs-24.* versions.
And yes helm support emacs-24.3.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by cheezy64** [comment]
Sorry to drag this out.  I think it's due to updating the emacs version.  I had updated and reproduced the bug on 24.3.  It still had the behavior described in this issue.  I then I used homebrew to install 24.5.1.  I did NOT do list-packages again to update.  Then, it behaved correctly.

So, in this case, the upgrade worked for me.  I don't think this needs to be examined anymore, I just wanted to leave a note in case someone else runs into this issue.

Thanks everyone for your help on this!
